vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/book_covers
            upload_destination: '%kernel.project_dir%/public/images/book_covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
